from enum import Enum


class DeviceEventType(str, Enum):
    SCHEDULER = "SCHEDULER"


class DeviceEventName(str, Enum):
    SCHEDULER_TRIGGER_ON = "SCHEDULER_TRIGGER_ON"
    SCHEDULER_SKIPPED_NO_POWER_DATA = "SCHEDULER_SKIPPED_NO_POWER_DATA"
    SCHEDULER_SKIPPED_THRESHOLD_NOT_MET = "SCHEDULER_SKIPPED_THRESHOLD_NOT_MET"
    SCHEDULER_ACK_FAILED = "SCHEDULER_ACK_FAILED"

